using Microsoft.EntityFrameworkCore;
using Sepidar.Domain.Entities;

namespace Sepidar.Repository.Implementation
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        {
        }

         public DbSet<FormulaBomItem> FormulaBomItems { get; set; }
  public DbSet<FormulaBomItemAlternative> FormulaBomItemAlternatives { get; set; }
  public DbSet<ProductFormula> ProductFormulas { get; set; }
  public DbSet<ProductOrder> ProductOrders { get; set; }
  public DbSet<ProductOrderBOMItem> ProductOrderBOMItems { get; set; }
  public DbSet<AdditionFactor> AdditionFactors { get; set; }
  public DbSet<AdditionFactorItem> AdditionFactorItems { get; set; }
  public DbSet<Commission> Commissions { get; set; }
  public DbSet<CommissionArea> CommissionAreas { get; set; }
  public DbSet<CommissionBroker> CommissionBrokers { get; set; }
  public DbSet<CommissionCalculation> CommissionCalculations { get; set; }
  public DbSet<CommissionCalculationInvoice> CommissionCalculationInvoices { get; set; }
  public DbSet<CommissionCalculationItem> CommissionCalculationItems { get; set; }
  public DbSet<CommissionCalculationXMLResult> CommissionCalculationXMLResults { get; set; }
  public DbSet<CommissionItem> CommissionItems { get; set; }
  public DbSet<CommissionStep> CommissionSteps { get; set; }
  public DbSet<Discount> Discounts { get; set; }
  public DbSet<DiscountItem> DiscountItems { get; set; }
  public DbSet<Invoice> Invoices { get; set; }
  public DbSet<InvoiceBroker> InvoiceBrokers { get; set; }
  public DbSet<InvoiceCommissionBroker> InvoiceCommissionBrokers { get; set; }
  public DbSet<InvoiceItem> InvoiceItems { get; set; }
  public DbSet<InvoiceItemAdditionFactor> InvoiceItemAdditionFactors { get; set; }
  public DbSet<InvoiceReceiptChequeInfo> InvoiceReceiptChequeInfos { get; set; }
  public DbSet<InvoiceReceiptInfo> InvoiceReceiptInfos { get; set; }
  public DbSet<ItemAdditionFactor> ItemAdditionFactors { get; set; }
  public DbSet<ItemDiscount> ItemDiscounts { get; set; }
  public DbSet<PriceNote> PriceNotes { get; set; }
  public DbSet<PriceNoteItem> PriceNoteItems { get; set; }
  public DbSet<PriceNoteItemDiscount> PriceNoteItemDiscounts { get; set; }
  public DbSet<ProductPack> ProductPacks { get; set; }
  public DbSet<ProductPackDiscount> ProductPackDiscounts { get; set; }
  public DbSet<ProductPackItem> ProductPackItems { get; set; }
  public DbSet<Quotation> Quotations { get; set; }
  public DbSet<QuotationCommissionBroker> QuotationCommissionBrokers { get; set; }
  public DbSet<QuotationItem> QuotationItems { get; set; }
  public DbSet<QuotationItemAdditionFactor> QuotationItemAdditionFactors { get; set; }
  public DbSet<ReturnedInvoice> ReturnedInvoices { get; set; }
  public DbSet<ReturnedInvoiceBroker> ReturnedInvoiceBrokers { get; set; }
  public DbSet<ReturnedInvoiceCommissionBroker> ReturnedInvoiceCommissionBrokers { get; set; }
  public DbSet<ReturnedInvoiceItem> ReturnedInvoiceItems { get; set; }
  public DbSet<ReturnedInvoiceItemAdditionFactor> ReturnedInvoiceItemAdditionFactors { get; set; }
  public DbSet<SaleType> SaleTypes { get; set; }
  public DbSet<Scheduling> Schedulings { get; set; }
  public DbSet<SchedulingItem> SchedulingItems { get; set; }
  public DbSet<AccountType> AccountTypes { get; set; }
  public DbSet<Bank> Banks { get; set; }
  public DbSet<BankAccount> BankAccounts { get; set; }
  public DbSet<BankAccountBalance> BankAccountBalances { get; set; }
  public DbSet<BankBill> BankBills { get; set; }
  public DbSet<BankBillItem> BankBillItems { get; set; }
  public DbSet<BankBranch> BankBranchs { get; set; }
  public DbSet<Cash> Cashs { get; set; }
  public DbSet<CashBalance> CashBalances { get; set; }
  public DbSet<ChequeBook> ChequeBooks { get; set; }
  public DbSet<DocSpecification> DocSpecifications { get; set; }
  public DbSet<PartyAccountSettlement> PartyAccountSettlements { get; set; }
  public DbSet<PartyAccountSettlementItem> PartyAccountSettlementItems { get; set; }
  public DbSet<PartySettlement> PartySettlements { get; set; }
  public DbSet<PartySettlementItem> PartySettlementItems { get; set; }
  public DbSet<PaymentCheque> PaymentCheques { get; set; }
  public DbSet<PaymentChequeBanking> PaymentChequeBankings { get; set; }
  public DbSet<PaymentChequeBankingItem> PaymentChequeBankingItems { get; set; }
  public DbSet<PaymentChequeHistory> PaymentChequeHistorys { get; set; }
  public DbSet<PaymentChequeOther> PaymentChequeOthers { get; set; }
  public DbSet<PaymentDraft> PaymentDrafts { get; set; }
  public DbSet<PaymentHeader> PaymentHeaders { get; set; }
  public DbSet<Pos> Poss { get; set; }
  public DbSet<PosBalance> PosBalances { get; set; }
  public DbSet<PosSettlement> PosSettlements { get; set; }
  public DbSet<PosSettlementReceipt> PosSettlementReceipts { get; set; }
  public DbSet<ReceiptCheque> ReceiptCheques { get; set; }
  public DbSet<ReceiptChequeBanking> ReceiptChequeBankings { get; set; }
  public DbSet<ReceiptChequeBankingItem> ReceiptChequeBankingItems { get; set; }
  public DbSet<ReceiptChequeHistory> ReceiptChequeHistorys { get; set; }
  public DbSet<ReceiptDraft> ReceiptDrafts { get; set; }
  public DbSet<ReceiptHeader> ReceiptHeaders { get; set; }
  public DbSet<ReceiptPos> ReceiptPoss { get; set; }
  public DbSet<Reconciliation> Reconciliations { get; set; }
  public DbSet<ReconciliationBankItem> ReconciliationBankItems { get; set; }
  public DbSet<ReconciliationItem> ReconciliationItems { get; set; }
  public DbSet<RefundCheque> RefundCheques { get; set; }
  public DbSet<RefundChequeItem> RefundChequeItems { get; set; }
  public DbSet<Cashier> Cashiers { get; set; }
  public DbSet<POSInvoice> POSInvoices { get; set; }
  public DbSet<POSInvoiceItem> POSInvoiceItems { get; set; }
  public DbSet<QuickBar> QuickBars { get; set; }
  public DbSet<QuickBarItem> QuickBarItems { get; set; }
  public DbSet<POSReturnedInvoice> POSReturnedInvoices { get; set; }
  public DbSet<POSReturnedInvoiceItem> POSReturnedInvoiceItems { get; set; }
  public DbSet<POSSettlement> POSSettlements { get; set; }
  public DbSet<POSSettlementItem> POSSettlementItems { get; set; }
  public DbSet<BillOfLoading> BillOfLoadings { get; set; }
  public DbSet<BillOfLoadingItem> BillOfLoadingItems { get; set; }
  public DbSet<CommercialOrder> CommercialOrders { get; set; }
  public DbSet<CommercialOrderItem> CommercialOrderItems { get; set; }
  public DbSet<Customs> Customss { get; set; }
  public DbSet<CustomsClearance> CustomsClearances { get; set; }
  public DbSet<CustomsClearanceItem> CustomsClearanceItems { get; set; }
  public DbSet<InsurancePolicy> InsurancePolicys { get; set; }
  public DbSet<InsurancePolicyItem> InsurancePolicyItems { get; set; }
  public DbSet<Performa> Performas { get; set; }
  public DbSet<PerformaItem> PerformaItems { get; set; }
  public DbSet<PurchaseCost> PurchaseCosts { get; set; }
  public DbSet<PurchaseCostItem> PurchaseCostItems { get; set; }
  public DbSet<PurchaseInvoice> PurchaseInvoices { get; set; }
  public DbSet<PurchaseInvoiceItem> PurchaseInvoiceItems { get; set; }
  public DbSet<PurchaseOrder> PurchaseOrders { get; set; }
  public DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
  public DbSet<PurchaseOtherCostItem> PurchaseOtherCostItems { get; set; }
  public DbSet<Branch> Branchs { get; set; }
  public DbSet<Calculation> Calculations { get; set; }
  public DbSet<PayContract> PayContracts { get; set; }
  public DbSet<ContractElement> ContractElements { get; set; }
  public DbSet<DailyHourMinute> DailyHourMinutes { get; set; }
  public DbSet<Element> Elements { get; set; }
  public DbSet<ElementItem> ElementItems { get; set; }
  public DbSet<Job> Jobs { get; set; }
  public DbSet<Leave> Leaves { get; set; }
  public DbSet<Loan> Loans { get; set; }
  public DbSet<MonthlyData> MonthlyDatas { get; set; }
  public DbSet<MonthlyDataPersonnel> MonthlyDataPersonnels { get; set; }
  public DbSet<MonthlyDataPersonnelElement> MonthlyDataPersonnelElements { get; set; }
  public DbSet<PayrollCalendar> PayrollCalendars { get; set; }
  public DbSet<PayrollConfiguration> PayrollConfigurations { get; set; }
  public DbSet<PayrollConfigurationElement> PayrollConfigurationElements { get; set; }
  public DbSet<Personnel> Personnels { get; set; }
  public DbSet<PersonnelInitiate> PersonnelInitiates { get; set; }
  public DbSet<PersonnelInitiateElement> PersonnelInitiateElements { get; set; }
  public DbSet<PersonnelTaxFileInfoChangeLog> PersonnelTaxFileInfoChangeLogs { get; set; }
  public DbSet<PiofyAttendanceFactor> PiofyAttendanceFactors { get; set; }
  public DbSet<PiofyAttendanceFactorMapper> PiofyAttendanceFactorMappers { get; set; }
  public DbSet<PiofyMonthlyCalculation> PiofyMonthlyCalculations { get; set; }
  public DbSet<PaySettlement> PaySettlements { get; set; }
  public DbSet<PaySettlementItem> PaySettlementItems { get; set; }
  public DbSet<TaxGroup> TaxGroups { get; set; }
  public DbSet<TaxTable> TaxTables { get; set; }
  public DbSet<TaxTableItem> TaxTableItems { get; set; }
  public DbSet<WorkExperience> WorkExperiences { get; set; }
  public DbSet<Worksite> Worksites { get; set; }
  public DbSet<CustomContact> CustomContacts { get; set; }
  public DbSet<CustomContactPhone> CustomContactPhones { get; set; }
  public DbSet<Inbox> Inboxs { get; set; }
  public DbSet<Message1> Message1s { get; set; }
  public DbSet<MessageContact> MessageContacts { get; set; }
  public DbSet<OutgoingMessage> OutgoingMessages { get; set; }
  public DbSet<PhoneLine> PhoneLines { get; set; }
  public DbSet<SentScheduledTemplateSchedulingDate> SentScheduledTemplateSchedulingDates { get; set; }
  public DbSet<Template> Templates { get; set; }
  public DbSet<TemplateContact> TemplateContacts { get; set; }
  public DbSet<TemplateEvent> TemplateEvents { get; set; }
  public DbSet<TemplateFilter> TemplateFilters { get; set; }
  public DbSet<TemplateScheduling> TemplateSchedulings { get; set; }
  public DbSet<CompoundBarcode> CompoundBarcodes { get; set; }
  public DbSet<Group> Groups { get; set; }
  public DbSet<InventoryBalancing> InventoryBalancings { get; set; }
  public DbSet<InventoryBalancingItem> InventoryBalancingItems { get; set; }
  public DbSet<InventoryDelivery> InventoryDeliverys { get; set; }
  public DbSet<InventoryDeliveryItem> InventoryDeliveryItems { get; set; }
  public DbSet<InventoryPricing> InventoryPricings { get; set; }
  public DbSet<InventoryPricingVoucher> InventoryPricingVouchers { get; set; }
  public DbSet<InventoryPricingVoucherItem> InventoryPricingVoucherItems { get; set; }
  public DbSet<InventoryPurchaseInvoice> InventoryPurchaseInvoices { get; set; }
  public DbSet<InventoryPurchaseInvoiceItem> InventoryPurchaseInvoiceItems { get; set; }
  public DbSet<InventoryReceipt> InventoryReceipts { get; set; }
  public DbSet<InventoryReceiptItem> InventoryReceiptItems { get; set; }
  public DbSet<InventoryWeighbridge> InventoryWeighbridges { get; set; }
  public DbSet<InventoryWeighbridgeConfiguration> InventoryWeighbridgeConfigurations { get; set; }
  public DbSet<InventoryWeighing> InventoryWeighings { get; set; }
  public DbSet<Item> Items { get; set; }
  public DbSet<ItemCategory> ItemCategorys { get; set; }
  public DbSet<ItemImage> ItemImages { get; set; }
  public DbSet<ItemPropertyAmount> ItemPropertyAmounts { get; set; }
  public DbSet<ItemStock> ItemStocks { get; set; }
  public DbSet<ItemStockSummary> ItemStockSummarys { get; set; }
  public DbSet<PricingItemPrice> PricingItemPrices { get; set; }
  public DbSet<ProducedItemPrice> ProducedItemPrices { get; set; }
  public DbSet<Property> Propertys { get; set; }
  public DbSet<PropertyDetail> PropertyDetails { get; set; }
  public DbSet<Stock> Stocks { get; set; }
  public DbSet<Tracing> Tracings { get; set; }
  public DbSet<TracingCategory> TracingCategorys { get; set; }
  public DbSet<Unit> Units { get; set; }
  public DbSet<VoucherItemTracking> VoucherItemTrackings { get; set; }
  public DbSet<AutomaticBackupConfig> AutomaticBackupConfigs { get; set; }
  public DbSet<Backup> Backups { get; set; }
  public DbSet<Bill> Bills { get; set; }
  public DbSet<BillItem> BillItems { get; set; }
  public DbSet<CalculationElement> CalculationElements { get; set; }
  public DbSet<CalculationFormula> CalculationFormulas { get; set; }
  public DbSet<ClosingOperation> ClosingOperations { get; set; }
  public DbSet<Communication> Communications { get; set; }
  public DbSet<CommunicationConfiguration> CommunicationConfigurations { get; set; }
  public DbSet<CostCenter> CostCenters { get; set; }
  public DbSet<Currency> Currencys { get; set; }
  public DbSet<CurrencyExchangeRate> CurrencyExchangeRates { get; set; }
  public DbSet<DebitCreditNote> DebitCreditNotes { get; set; }
  public DbSet<DebitCreditNoteItem> DebitCreditNoteItems { get; set; }
  public DbSet<DeliveryLocation> DeliveryLocations { get; set; }
  public DbSet<Device> Devices { get; set; }
  public DbSet<DeviceUserParty> DeviceUserPartys { get; set; }
  public DbSet<ElementSavedValue> ElementSavedValues { get; set; }
  public DbSet<EstablishmentCommunication> EstablishmentCommunications { get; set; }
  public DbSet<FormulaElement> FormulaElements { get; set; }
  public DbSet<Grouping> Groupings { get; set; }
  public DbSet<Location> Locations { get; set; }
  public DbSet<Logo> Logos { get; set; }
  public DbSet<MarketingDiskette> MarketingDiskettes { get; set; }
  public DbSet<MarketingDiskette1396> MarketingDiskette1396s { get; set; }
  public DbSet<MarketingDisketteCurrency> MarketingDisketteCurrencys { get; set; }
  public DbSet<MarketingDisketteCurrencyMapper> MarketingDisketteCurrencyMappers { get; set; }
  public DbSet<MarketingDisketteItem> MarketingDisketteItems { get; set; }
  public DbSet<MarketingDisketteItem1396> MarketingDisketteItem1396s { get; set; }
  public DbSet<MarketingDiskettePartyMapper> MarketingDiskettePartyMappers { get; set; }
  public DbSet<MarketingDiskettItemCategoryMapper> MarketingDiskettItemCategoryMappers { get; set; }
  public DbSet<Party> Partys { get; set; }
  public DbSet<PartyAddress> PartyAddresss { get; set; }
  public DbSet<PartyOpeningBalance> PartyOpeningBalances { get; set; }
  public DbSet<PartyPhone> PartyPhones { get; set; }
  public DbSet<PartyRelated> PartyRelateds { get; set; }
  public DbSet<PiofyEmployeeMapper> PiofyEmployeeMappers { get; set; }
  public DbSet<Shred> Shreds { get; set; }
  public DbSet<ShredInfo> ShredInfos { get; set; }
  public DbSet<ShredItem> ShredItems { get; set; }
  public DbSet<Truck> Trucks { get; set; }
  public DbSet<Vat> Vats { get; set; }
  public DbSet<VatItem> VatItems { get; set; }
  public DbSet<ApiLog> ApiLogs { get; set; }
  public DbSet<CheckDataParity> CheckDataParitys { get; set; }
  public DbSet<CheckDataParityItem> CheckDataParityItems { get; set; }
  public DbSet<Configuration> Configurations { get; set; }
  public DbSet<ExtraColumnDescription> ExtraColumnDescriptions { get; set; }
  public DbSet<ExtraData> ExtraDatas { get; set; }
  public DbSet<FAQ> FAQs { get; set; }
  public DbSet<FiscalYear> FiscalYears { get; set; }
  public DbSet<IDGeneration> IDGenerations { get; set; }
  public DbSet<ImportExportTemplate> ImportExportTemplates { get; set; }
  public DbSet<Keyword> Keywords { get; set; }
  public DbSet<KeywordLocale> KeywordLocales { get; set; }
  public DbSet<Lookup> Lookups { get; set; }
  public DbSet<LookupLocale> LookupLocales { get; set; }
  public DbSet<Note> Notes { get; set; }
  public DbSet<NumberedEntity> NumberedEntitys { get; set; }
  public DbSet<StandardDescription> StandardDescriptions { get; set; }
  public DbSet<User> Users { get; set; }
  public DbSet<UserAccess> UserAccesss { get; set; }
  public DbSet<UserConfiguration> UserConfigurations { get; set; }
  public DbSet<UserPhone> UserPhones { get; set; }
  public DbSet<UserReports> UserReportss { get; set; }
  public DbSet<UserReportsInvisible> UserReportsInvisibles { get; set; }
  public DbSet<Version1> Version1s { get; set; }
  public DbSet<AreaAndPath> AreaAndPaths { get; set; }
  public DbSet<ColdDistribution> ColdDistributions { get; set; }
  public DbSet<ColdDistributionInvoice> ColdDistributionInvoices { get; set; }
  public DbSet<ColdDistributionReturnedInvoice> ColdDistributionReturnedInvoices { get; set; }
  public DbSet<DebtCollectionList> DebtCollectionLists { get; set; }
  public DbSet<DebtCollectionListInvoice> DebtCollectionListInvoices { get; set; }
  public DbSet<HotDistribution> HotDistributions { get; set; }
  public DbSet<HotDistributionInventoryDelivery> HotDistributionInventoryDeliverys { get; set; }
  public DbSet<HotDistributionItem> HotDistributionItems { get; set; }
  public DbSet<HotDistributionPath> HotDistributionPaths { get; set; }
  public DbSet<HotDistributionSaleDocument> HotDistributionSaleDocuments { get; set; }
  public DbSet<HotDistributionUnexecutedAct> HotDistributionUnexecutedActs { get; set; }
  public DbSet<Order> Orders { get; set; }
  public DbSet<OrderingFailure> OrderingFailures { get; set; }
  public DbSet<OrderingFailureItem> OrderingFailureItems { get; set; }
  public DbSet<OrderingSchedule> OrderingSchedules { get; set; }
  public DbSet<OrderingScheduleRecurrence> OrderingScheduleRecurrences { get; set; }
  public DbSet<OrderingScheduleRelatedActivities> OrderingScheduleRelatedActivitiess { get; set; }
  public DbSet<OrderItem> OrderItems { get; set; }
  public DbSet<OrderItemAdditionFactor> OrderItemAdditionFactors { get; set; }
  public DbSet<PathPartyAddress> PathPartyAddresss { get; set; }
  public DbSet<ProductSaleLine> ProductSaleLines { get; set; }
  public DbSet<ProductSaleLineItem> ProductSaleLineItems { get; set; }
  public DbSet<ProductSaleLineParty> ProductSaleLinePartys { get; set; }
  public DbSet<ReturnOrder> ReturnOrders { get; set; }
  public DbSet<ReturnOrderItem> ReturnOrderItems { get; set; }
  public DbSet<ReturnOrderItemAdditionFactor> ReturnOrderItemAdditionFactors { get; set; }
  public DbSet<ReturnReason> ReturnReasons { get; set; }
  public DbSet<SalesLimit> SalesLimits { get; set; }
  public DbSet<SalesLimitItem> SalesLimitItems { get; set; }
  public DbSet<SalesLimitItemParty> SalesLimitItemPartys { get; set; }
  public DbSet<SaleTypeConstraint> SaleTypeConstraints { get; set; }
  public DbSet<SaleTypeConstraintItem> SaleTypeConstraintItems { get; set; }
  public DbSet<UnexecutedActReason> UnexecutedActReasons { get; set; }
  public DbSet<ChangeItem> ChangeItems { get; set; }
  public DbSet<Coefficient> Coefficients { get; set; }
  public DbSet<Contract> Contracts { get; set; }
  public DbSet<ContractAgreementItem> ContractAgreementItems { get; set; }
  public DbSet<ContractCoefficientItem> ContractCoefficientItems { get; set; }
  public DbSet<ContractCompromiseItem> ContractCompromiseItems { get; set; }
  public DbSet<ContractEmployerMaterialsItem> ContractEmployerMaterialsItems { get; set; }
  public DbSet<ContractPreReceiptItem> ContractPreReceiptItems { get; set; }
  public DbSet<ContractPriceList> ContractPriceLists { get; set; }
  public DbSet<ContractRelatedPurchaseInvoice> ContractRelatedPurchaseInvoices { get; set; }
  public DbSet<ContractSupportingInsurance> ContractSupportingInsurances { get; set; }
  public DbSet<ContractType> ContractTypes { get; set; }
  public DbSet<ContractWarrantyItem> ContractWarrantyItems { get; set; }
  public DbSet<ContractWorkshopItem> ContractWorkshopItems { get; set; }
  public DbSet<Cost> Costs { get; set; }
  public DbSet<CostStatement> CostStatements { get; set; }
  public DbSet<CostStatementItem> CostStatementItems { get; set; }
  public DbSet<Guarantee> Guarantees { get; set; }
  public DbSet<GuaranteeOperation> GuaranteeOperations { get; set; }
  public DbSet<GuaranteeRelated> GuaranteeRelateds { get; set; }
  public DbSet<Project> Projects { get; set; }
  public DbSet<ContractSettlement> ContractSettlements { get; set; }
  public DbSet<SettlementDebtItem> SettlementDebtItems { get; set; }
  public DbSet<SettlementItem> SettlementItems { get; set; }
  public DbSet<Status> Statuss { get; set; }
  public DbSet<StatusCoefficientItem> StatusCoefficientItems { get; set; }
  public DbSet<StatusItem> StatusItems { get; set; }
  public DbSet<StatusOnAccountItem> StatusOnAccountItems { get; set; }
  public DbSet<StatusReceiptItem> StatusReceiptItems { get; set; }
  public DbSet<Tender> Tenders { get; set; }
  public DbSet<Warranty> Warrantys { get; set; }
  public DbSet<Workshop> Workshops { get; set; }
  public DbSet<AcquisitionReceipt> AcquisitionReceipts { get; set; }
  public DbSet<AcquisitionReceiptItem> AcquisitionReceiptItems { get; set; }
  public DbSet<Asset> Assets { get; set; }
  public DbSet<AssetClass> AssetClasss { get; set; }
  public DbSet<AssetGroup> AssetGroups { get; set; }
  public DbSet<AssetRelatedPurchaseInvoice> AssetRelatedPurchaseInvoices { get; set; }
  public DbSet<AssetTransaction> AssetTransactions { get; set; }
  public DbSet<ChangeDepreciationMethod> ChangeDepreciationMethods { get; set; }
  public DbSet<ChangeDepreciationMethodItem> ChangeDepreciationMethodItems { get; set; }
  public DbSet<CostPart> CostParts { get; set; }
  public DbSet<CostPartTransaction> CostPartTransactions { get; set; }
  public DbSet<Depreciation> Depreciations { get; set; }
  public DbSet<DepreciationItem> DepreciationItems { get; set; }
  public DbSet<DepreciationRule> DepreciationRules { get; set; }
  public DbSet<Elimination> Eliminations { get; set; }
  public DbSet<EliminationItem> EliminationItems { get; set; }
  public DbSet<Emplacement> Emplacements { get; set; }
  public DbSet<Repair> Repairs { get; set; }
  public DbSet<RepairItem> RepairItems { get; set; }
  public DbSet<Sale> Sales { get; set; }
  public DbSet<SaleItem> SaleItems { get; set; }
  public DbSet<Salvage> Salvages { get; set; }
  public DbSet<SalvageItem> SalvageItems { get; set; }
  public DbSet<Transfer> Transfers { get; set; }
  public DbSet<TransferItem> TransferItems { get; set; }
  public DbSet<Unuseable> Unuseables { get; set; }
  public DbSet<UnuseableItem> UnuseableItems { get; set; }
  public DbSet<Useable> Useables { get; set; }
  public DbSet<UseableItem> UseableItems { get; set; }
  public DbSet<Account> Accounts { get; set; }
  public DbSet<AccountTopic> AccountTopics { get; set; }
  public DbSet<DL> DLs { get; set; }
  public DbSet<GLVoucher> GLVouchers { get; set; }
  public DbSet<GLVoucherItem> GLVoucherItems { get; set; }
  public DbSet<OpeningOperation> OpeningOperations { get; set; }
  public DbSet<OpeningOperationItem> OpeningOperationItems { get; set; }
  public DbSet<Topic> Topics { get; set; }
  public DbSet<Voucher> Vouchers { get; set; }
  public DbSet<VoucherItem> VoucherItems { get; set; }
 

        protected override void OnModelCreating(ModelBuilder builder)
        {
            
        }
    }
}
